log_level: error
zeroconf_enabled: false
mpris_enabled: true
audio_backend: alsa
device_name: lazyspotify
credentials:
    type: spotify_token
    spotify_token:
        username: 31zbnzgabg4paiyned3mavt5kj6e
        access_token: BQAOAbZmn2ssSLaOP_rBNYfRVqHA8FgPL5FJ_uuJllAS3zxShuMXwx8doJsWS6JPnzqlwkVdxEKPeDLkoqyrAaHl6IFyk7Mug8XJ4UyqyIKDkB85i4sfSHnZIhhGDKhBruh4JlBNcGVa7iJjM-tQs95kZ5hWDBOcpmhjfzI4IthuGGBuJHWJ49st4MZ2djTp3XY6iTkUVAYkDigY5e58ulcCt_CGMd8hyfTAptnWl7AjO96YtU2kbIJwEXzQKgxKFUgKtXCB4eh_O0XJCrdGrsu-lKvkf58ybmCzKTz0Q5aBJg0
server:
    enabled: true
    address: 127.0.0.1
    port: 4040
    allow_origin: '*'
    cert_file: ""
    key_file: ""
    image_size: small
