preload = /home/Woeter/Pictures/Wallpapers/C3A5CWindows5CTEMP5Ccatppuccinifier5Cmocha-hald8-98b0d2b9-a54a-1e76-c3e3-c560d48c766b_desktop-b016_ds_clarensgoldengatesa_shutterstock_490044154_3840x2160.png

wallpaper {
    monitor = eDP-1
    path = /home/Woeter/Pictures/Wallpapers/C3A5CWindows5CTEMP5Ccatppuccinifier5Cmocha-hald8-98b0d2b9-a54a-1e76-c3e3-c560d48c766b_desktop-b016_ds_clarensgoldengatesa_shutterstock_490044154_3840x2160.png
    fit_mode = cover
}

splash = false
ipc = on
