[AlsaMidi]
Enabled=true

[FilterNodes]
Enabled=false
List=@Invalid()

[GraphCanvas]
CanvasRect="@Variant(\0\0\0\x14\xc0\x83\xfd\xd7\n=p\xa4\xc0\x90\xd2\\(\xf5\xc2\x90@\x99\r\xd7\n=p\xa4@\xa3\x4\\(\xf5\xc2\x90)"
CanvasZoom=1

[GraphColors]
0x172973e6=#006b6b
0x2c2fdc12=#6b006b
0x30fc78a9=#6b0000
0x50c34e7e=#6b6b00
0xb91441cf=#006b00

[GraphGeometry]
qpwgraph_main=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\aS\0\0\x3\xe7\0\0\0\0\0\0\0\0\0\0\x3\xa2\0\0\x3\xe7\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\aS\0\0\x3\xe7)

[GraphLayout]
qpwgraph_main=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\aT\0\0\x3i\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x2\0\0\0\x2\0\0\0\x1\0\0\0\x18\0g\0r\0\x61\0p\0h\0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\x1\0\0\0\x1e\0p\0\x61\0t\0\x63\0h\0\x62\0\x61\0y\0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[GraphNodePos]
14%3AMidi%20Through%3AInput=@Variant(\0\0\0\x1a@r\xc0\0\0\0\0\0\xc0\x82`\0\0\0\0\0)
14%3AMidi%20Through%3AOutput=@Variant(\0\0\0\x1a\xc0t\0\0\0\0\0\0@\x8a\0\0\0\0\0\0)
AB13X%20Headset%20Adapter%20Analog%20Stereo%20%5BMonitor%5D=@Variant(\0\0\0\x1a\xc0\x38\0\0\0\0\0\0\xc0(\0\0\0\0\0\0)
AB13X%20Headset%20Adapter%20Analog%20Stereo%3AInput=@Variant(\0\0\0\x1a@r\xc0\0\0\0\0\0@q\0\0\0\0\0\0)
AB13X%20Headset%20Adapter%20Mono%3AOutput=@Variant(\0\0\0\x1a\xc0t@\0\0\0\0\0@p@\0\0\0\0\0)
BLE%20MIDI%201%3AInput=@Variant(\0\0\0\x1a@r@\0\0\0\0\0\xc0k\x80\0\0\0\0\0)
BLE%20MIDI%201%3AOutput=@Variant(\0\0\0\x1a\xc0s\xc0\0\0\0\0\0\xc0i\0\0\0\0\0\0)
Built-in%20Audio%20Analog%20Stereo%20%5BMonitor%5D=@Variant(\0\0\0\x1a@s\0\0\0\0\0\0\xc0\x38\0\0\0\0\0\0)
Built-in%20Audio%20Analog%20Stereo%3AInput=@Variant(\0\0\0\x1a@s\0\0\0\0\0\0\xc0x\0\0\0\0\0\0)
Built-in%20Audio%20Analog%20Stereo%3AOutput=@Variant(\0\0\0\x1a\xc0t\x80\0\0\0\0\0\xc0y@\0\0\0\0\0)
Firefox=@Variant(\0\0\0\x1a@]\0\0\0\0\0\0\xc0\x62\0\0\0\0\0\0)
Firefox-1%3AOutput=@Variant(\0\0\0\x1a\xc0t\0\0\0\0\0\0@\x84\xa0\0\0\0\0\0)
Firefox%3AOutput=@Variant(\0\0\0\x1a\xc0s\x80\0\0\0\0\0\xc0\x82 \0\0\0\0\0)
Midi-Bridge%3AInput=@Variant(\0\0\0\x1a@r\xc0\0\0\0\0\0@V\0\0\0\0\0\0)
Midi-Bridge%3AOutput=@Variant(\0\0\0\x1a\xc0s\xc0\0\0\0\0\0@S\0\0\0\0\0\0)
USB2.0%20HD%20UVC%20WebCam%20%28V4L2%29%3AOutput=@Variant(\0\0\0\x1a\xc0t\xc0\0\0\0\0\0@}@\0\0\0\0\0)
firefox%3AInput=@Variant(\0\0\0\x1a@y@\0\0\0\0\0@\x8f\xa0\0\0\0\0\0)
xdg-desktop-portal-hyprland%3AOutput=@Variant(\0\0\0\x1a\xc0t@\0\0\0\0\0\xc0\x88\xa0\0\0\0\0\0)

[GraphView]
ConnectThroughNodes=false
Menubar=true
RepelOverlappingNodes=false
SortOrder=0
SortType=0
Statusbar=true
TextBesideIcons=true
Thumbview=0
Toolbar=true
ZoomRange=false

[MergerNodes]
Enabled=false
List=@Invalid()

[Patchbay]
Activated=false
AutoDisconnect=false
AutoPin=true
Dir=
Exclusive=false
Path=
QueryQuit=true
RecentFiles=@Invalid()
Toolbar=true

[SystemTray]
Enabled=true
QueryClose=true
StartMinimized=false
