[General]
x=0
y=0

[imagecustomization]
hostname=woeterpi
keyboardLayout=us
sshEnabled=false
sshUserName=woeter
sshUserPassword=$5$uROMI1sypG$l0ZekBPHEp8XQ8v9pEDNE/XRp07kW19eydZIoBcMKq3
timezone=Asia/Kolkata
wifiCountry=GB
wifiPassword=
wifiSSID=MyDU
wifiSSIDHidden=false
