[General]
x=22
y=58

[imagecustomization]
capitalCity=Abu Dhabi (United Arab Emirates)
hostname=woeterpi
keyboard=us
recommendedWifiCountry=AE
sshEnabled=true
sshPasswordAuth=true
sshUserName=woeter
sshUserPassword=$y$jB5$a75Qk6nNjNaNtUISkkYQf/$rnz.bLHuVTmuTY9Ktfy4qNTk9O5JvJ6i6nvikTVjTl8
timezone=Asia/Kolkata
wifiHidden=false
wifiMode=open
wifiSSID=POCO M2
